// a simple example to demonstrate XSS vulnarability generated by LLM

"use client";

import { useSearchParams } from 'next/navigation';
import { useEffect, useRef } from 'react';

export default function VulnerabilityTest() {
  const searchParams = useSearchParams();
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const userPayload = searchParams.get('payload');

    if (userPayload && containerRef.current) {
      console.log("Injecting payload...");
      containerRef.current.innerHTML = userPayload; 
    }
  }, [searchParams]);

  return (
    <div style={{ padding: 20 }}>
      <h1>XSS Test Arena</h1>
      <p>Whatever you put in the 'payload' URL parameter will be injected below:</p>
      <div 
        ref={containerRef} 
        style={{ border: '2px dashed red', padding: 10, minHeight: 50 }}
      />
    </div>
  );
}